# Generated by Django 4.2.7 on 2025-12-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="busquedadominio",
            name="fecha_fin",
            field=models.DateTimeField(
                blank=True, help_text="Hora de finalización del crawling", null=True
            ),
        ),
    ]
