# Generated by Django 4.2.7 on 2025-12-12 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_busquedadominio_fecha_fin"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "progress_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("dominio", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=0)),
                ("last_url", models.TextField(blank=True)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "urls_found",
                    models.TextField(
                        blank=True, help_text="URLs encontradas separadas por |"
                    ),
                ),
                (
                    "busqueda_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID de BusquedaDominio relacionado",
                        null=True,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
