# Generated by Django 4.2.7 on 2025-12-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_crawlingprogress"),
    ]

    operations = []
