# Generated by Django 4.2.7 on 2025-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20251211_2118"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlingprogress",
            name="task_id",
            field=models.CharField(
                blank=True, help_text="ID de la tarea Celery", max_length=255, null=True
            ),
        ),
    ]
