# Generated by Django 4.2.7 on 2025-12-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_crawlingprogress_task_id"),
    ]

    operations = []
