# Generated by Django 4.2.7 on 2025-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20251212_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="busquedadominio",
            name="guardado",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el dominio ha sido marcado como guardado",
            ),
        ),
    ]
