# Generated by Django 4.2.7 on 2025-12-12 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_busquedadominio_guardado"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlGuardada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "url",
                    models.URLField(
                        help_text="URL individual guardada", max_length=2000
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Título de la página (opcional)",
                        max_length=500,
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        help_text="Dominio al que pertenece la URL", max_length=255
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas adicionales del usuario"
                    ),
                ),
                (
                    "busqueda_dominio",
                    models.ForeignKey(
                        help_text="Búsqueda de dominio de la que proviene esta URL",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.busquedadominio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuario que guardó la URL",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("url", "usuario")},
            },
        ),
    ]
