# Generated by Django 4.2.7 on 2025-12-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_urlguardada"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalisisUrlIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(help_text="URL a analizar", max_length=2000)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True,
                        help_text="Hora de finalización del análisis",
                        null=True,
                    ),
                ),
                (
                    "tipo_analisis",
                    models.CharField(
                        choices=[
                            ("seo", "SEO"),
                            ("accesibilidad", "Accesibilidad"),
                            ("links", "Links"),
                            ("todas", "Todas"),
                        ],
                        default="seo",
                        help_text="Tipo de análisis realizado",
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_progreso", "En progreso"),
                            ("finalizado", "Finalizado"),
                            ("error", "Error"),
                        ],
                        default="en_progreso",
                        max_length=20,
                    ),
                ),
                (
                    "resultados",
                    models.TextField(
                        blank=True, help_text="Resultados del análisis en formato JSON"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
