# Generated by Django 4.2.7 on 2025-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_analisisurlindividual"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisisurlindividual",
            name="alcance_analisis",
            field=models.CharField(
                choices=[("1", "1 URL"), ("todas", "Todas las URLs")],
                default="1",
                help_text="Alcance del análisis",
                max_length=20,
            ),
        ),
    ]
